limbo:
  test:
    dimension:
      name: 'first'
      # Available types: OVERWORLD, END, NETHER
      type: OVERWORLD
      # Optional
      # Change world time
      fixed-time: 0
    biome:
      # OCEAN, PLAINS, DESERT, FOREST, EXTREME_HILLS, TAIGA, SWAMP, RIVER, NETHER, THE_END, ICY, MUSHROOM, BEACH, JUNGLE, MESA, SAVANNA, NONE
      category: PLAINS
      # THE_VOID, PLAINS, SUNFLOWER_PLAINS, SNOWY_PLAINS, ICE_SPIKES, DESERT, SWAMP, MANGROVE_SWAMP, FOREST, FLOWER_FOREST, BIRCH_FOREST, DARK_FOREST,
      # OLD_GROWTH_BIRCH_FOREST, OLD_GROWTH_PINE_TAIGA, OLD_GROWTH_SPRUCE_TAIGA, TAIGA, SNOWY_TAIGA, SAVANNA, SAVANNA_PLATEAU, WINDSWEPT_HILLS,
      # WINDSWEPT_GRAVELLY_HILLS, WINDSWEPT_FOREST, WINDSWEPT_SAVANNA, JUNGLE, SPARSE_JUNGLE, BAMBOO_JUNGLE, BADLANDS, ERODED_BADLANDS, WOODED_BADLANDS,
      # MEADOW, GROVE, SNOWY_SLOPES, FROZEN_PEAKS, JAGGED_PEAKS, STONY_PEAKS, RIVER, FROZEN_RIVER, BEACH, SNOWY_BEACH, STONY_SHORE, WARM_OCEAN,
      # LUKEWARM_OCEAN, DEEP_LUKEWARM_OCEAN, OCEAN, DEEP_OCEAN, COLD_OCEAN, DEEP_COLD_OCEAN, FROZEN_OCEAN, DEEP_FROZEN_OCEAN, MUSHROOM_FIELDS,
      # DRIPSTONE_CAVES, LUSH_CAVES, DEEP_DARK, NETHER_WASTES, WARPED_FOREST, CRIMSON_FOREST, SOUL_SAND_VALLEY, BASALT_DELTAS, THE_END, END_HIGHLANDS,
      # END_MIDLANDS, SMALL_END_ISLANDS, END_BARRENS;
      type: PLAINS
    # Default spawn coordinates
    coordinates:
      x: 0.
      y: 0
      z: 0
      yaw: 0
      pitch: 0
    # Server name in f3 debug screen
    brand: 'Limbo'
    gamemode: 3